services:
  - type: web
    name: ghi-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 1 --threads 4 --timeout 600 --preload app:app"
    healthCheckPath: "/health"
    autoDeploy: true
